### PR TITLE
0.1 Release

### PR DESCRIPTION
**Pull request by ascott1**
This is the first pass at cf-icons. It contains
- generic cf-compontent project setup
- icon font files
- less for IE8+
- demo showing all of the icons (tested in Chrome, Firefox, Safari, IE9 and IE10)
## Known Issues
- IE8 displays empty boxes in place of icons
- Not yet IE7 compatible

### CODE REVIEW

**Comment by Scotchester** [comment]
Let's review and merge this PR as is to keep things neat and tidy, but after that is done, would you please convert this to a gh-pages only repo?

**Comment by Scotchester** [comment]
Please change `CONTRIBUTING.md` to follow our new paradigm: https://github.com/cfpb/cf-buttons/blob/gh-pages/CONTRIBUTING.md

**Comment by ascott1** [comment]
@Scotchester hand't realized that all of the cf- components were on gh-pages branches. I'll update that once this is merged

**Comment by ascott1** [comment]
`CONTRIBUTING.md` is updated

**Comment by Scotchester** [comment]
Thanks! Forgot to mention we're also similarly slimming-down the `README`. Could you take care of that, as well? Looks like it's good to go after that.

**Comment by ascott1** [comment]
README is slimmed. The links in to the docs and demo won't work, but once this is merged I'll move everything to gh-pages and we should be good to go there.

Thanks!

**Comment by Scotchester** [comment]
Lookin' good!

**Pull request merged**
