### PR TITLE
Updating package.json to include missing fields

### LINKED ISSUE #50: Add repository field to package.json
... or get `npm WARN package.json @ No repository field.`

### PR DESCRIPTION
**Pull request by KimberlyMunoz**
Updating package.json to include missing fields
## Additions
- Adding missing fields to package.json
## Review
- @contolini 
## Preview

[Preview this PR without the whitespace changes](?w=0)
## Notes
- Fixes #50

### CODE REVIEW

**Comment by jimmynotjim** [comment]
Thank you! :pray: Been on my mental list of eventual things do to forever. :+1:

**Comment by contolini** [comment]
:+1:

@scotchester and @himedlooff made a conscious decision back in the day to omit certain fields but AFAIK it was only for aesthetic reasons.

**Comment by KimberlyMunoz** [comment]
Is this one of those "someone else merges" repos?

**Comment by Scotchester** [comment]
The decision was based on reducing the maintenance burden, and the fact that we distribute components via Bower, not npm. We decided at the time to reduce package.json to the bare minimum fields necessary for our purposes. I don't feel strongly about it, though, if people want to put them back.

That said, on what did you base your choices for fields to re-add? Why not include `keywords`, `authors`, `homepage`, `main`? And why format the value of `license` differently? If we're going to have fields duplicated across the two JSON files, let's at least try to keep theme as consistent as possible.

**Comment by contolini** [comment]
We need emoji to indicate whether the PR submitter or the reviewer merges.

I vote :unlock: indicates anyone can merge and :lock: means only the person
who submitted the PR should merge it.

In this case :lock: because @scotchester has questions.

On Thursday, August 13, 2015, Kimberly Munoz notifications@github.com
wrote:

> Is this one of those "someone else merges" repos?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cfpb/cf-icons/pull/52#issuecomment-130934103.

## 

Chris

**Comment by KimberlyMunoz** [comment]
> Why not include keywords, authors, homepage, main?

Name, description and version are the most important fields to include. Bugs and repo are nice because [npm can point people to file issues via `npm bugs`](https://docs.npmjs.com/files/package.json#bugs).

Homepage seems like a good inclusion, but the others seemed ambiguous and up for debate as to what they could be filled with. Also being findable on search doesn't seem like a priority. Do we have an email address for a CFPB "author"? Either way it all seems like something that could be dealt with in another PR.

> And why format the value of license differently? 

License is different because we have a few exceptions to CC-0 that are detailed in our License.md file. [npm suggests pointing folks to a file in those cases.](https://docs.npmjs.com/files/package.json#license)

**Comment by KimberlyMunoz** [comment]
> We need emoji to indicate whether the PR submitter or the reviewer merges.

💯

**Comment by Scotchester** [comment]
My comment was geared toward making common fields in `bower.json` and `package.json` the same, as much as their specs allow, so we don't have to keep track of different values in the two files. Most of the answers to what the ambiguous fields should be filled with can be found in `bower.json`.

In this case,

``` json
...
  "keywords": ["capital-framework", "capital", "icons", "less"],
  "authors": [
    {
      "name": "Consumer Financial Protection Bureau",
      "url": "https://cfpb.github.io/"
    }
  ],
  "homepage": "https://github.com/cfpb/cf-icons",
  "repository": {
    "type": "git",
    "url": "https://github.com/cfpb/cf-icons.git"
  },
  "license": "https://github.com/cfpb/cf-icons/blob/gh-pages/TERMS.md",
  "main": "src/less/cf-icons.less",
…
```

Unfortunately, the specs differ on the formatting of `authors` (Bower) and `author`/`contributors` (npm). But those are the `name` and `url` values we standardized on, at least for CF packages. (`email` is not required in either spec.)

On the question of `license`, the implied second part of the question was "than the example in `bower.json`", which is already the URL to `TERMS.md`. Thanks for the link to the example given in the npm spec, though. From my reading of the SPDX License Expression spec, I don't see how "SEE LICENSE IN filename" is valid, but if that's what the npm spec recommends, I guess it's fine to leave it that way.

This issue makes me realize, though, that these CF packages are pretty out-of-step with how things are being handled in generator-cf now: [`_bower.json`](https://github.com/cfpb/generator-cf/blob/master/app/templates/_bower.json) [`_package.json`](https://github.com/cfpb/generator-cf/blob/master/app/templates/_package.json). This may need to turn into a wider effort that also requires updating the generator so that fields like license correctly follow each file's spec.

**Comment by KimberlyMunoz** [comment]
I think our vacations just overlapped, Scott.

Thanks for the suggestions. I see what you mean. I'll go ahead and add the missing fields that are included in bower.json and leave the license towards what npm is recommending.

Last point about standardizing across other cf-packages. I completely :+1: agree. I think I went through and assigned myself relevant issues in other repos where I found them. Once we get one agreed on and merged, the following PRs should be easier.

**Comment by KimberlyMunoz** [comment]
Hey @Scotchester. I gave `package.json` an update. Let me know if there's any additional fixes.

**Comment by Scotchester** [comment]
Whoops! Looks like our vacations did indeed throw this off the rails :)

Looks good now, thanks! :+1:

**Pull request merged**
