### PR TITLE
Adding newest cf-icons

### PR DESCRIPTION
**Pull request by KimberlyMunoz**
### Added
- Adds icons for history, table of contents, closing quote, livestream, parents and servicemembers

screenshot

### CODE REVIEW

**Comment by ascott1** [comment]
Nice! Thanks for adding these @KimberlyMunoz!

**Comment by KimberlyMunoz** [comment]
On IE 6/8/9

image

**Comment by KimberlyMunoz** [comment]
_IE 6_
image

_IE 7 (Sauce)_
image

_IE 8_
image

_IE 9_
image

**Comment by anselmbradford** [comment]
IE 7 ??? :stuck_out_tongue_winking_eye:

**Comment by KimberlyMunoz** [comment]
IE 7 is the worst... and busted on my machine, so hold tight.

**Comment by Scotchester** [comment]
> IE 6 ?!?!?! :rage4: 

FTFY, @anselmbradford

**Comment by anselmbradford** [comment]
Haha @Scotchester that's a collision of painfully unfun and fun old memories..

**Comment by Scotchester** [comment]
In all seriousness, we don't support IE6. Don't spend any time on it. And it's debatable how much longer we're going to support IE7.

**Comment by ascott1** [comment]
:+1: Nicely done.

**Comment by anselmbradford** [comment]
Tagged a release for this so we can pull it into cfgov-refresh... hope that was alright! Edit as needed.

**Pull request merged**
